apiVersion: v1
kind: Secret
metadata:
    name: slack-credentials
    namespace: mother-tree
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:86Qrmjj0/nIezFYgXpIAg37JbWEL/HddclFVb+1VpnK0fJhyI7x91Om9WFimYflDqVCkeEhIbg==,iv:Kjvwo+4SFpzPmGx8Uyo6mCFAV7LKuuYedzWv0CQNEoo=,tag:eeumVLqfJZ9BDsd5LvmGFg==,type:str]
    app-token: ENC[AES256_GCM,data:mNdIBn+d5fMrNvyUZajLSlpgPBl9T9bXO1ADjChPCL4JM4YE09pCf8EnV53D7UYHpl38B2pXkBSYHjeX7Q61PBj5BAIuIFKAorJbpwF9Y3BNZL1kQHqD6EcqvWCQQYtuQCs=,iv:brScrCxDgUiVEwsRKW8SdT7tDrpyUmw52bGpc/Qa1kg=,tag:ynfDDmUeP1T6dQtmi8d1yw==,type:str]
    admin-email: ENC[AES256_GCM,data:yp2aZud8zpqXzdzzAU0prKg=,iv:x3+3ICYKU7LBIX9Pbq+hohqvk2gdHKHsfxWuOhup0EI=,tag:Dt5vEoyt55sU7jVGMNh7Ew==,type:str]
sops:
    age:
        - recipient: age1ny5rpz82l25pxw3esxrv6e2g5wy3j09uwgmwu6ygh6q9k6jajp3srl0ru5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXlmQmd4QSswUHlZNVZm
            L2JhazE1TmxDbDJSM2NKTnVTNEZobFNqUVQ4CmVqNVJxK0JLQ1ZrSkN3SHFpTmhh
            MGM5dm55OVcreVEyV1AyY0J5Y1d0ZUkKLS0tIHYrbmhzWG85UXNQeHlnS1R3dVVI
            THdRNkRpVVBUdGpxZzFIUjNYazhxVnMKdGLs7YA4IlZPb7ki8oRZ8lz6LFRmclb3
            e2eXdgp0GzanUCyhBrColh+3dAmpCOM3yX5S+9eNHkMhayJ+KehdwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:50:54Z"
    mac: ENC[AES256_GCM,data:sbEZ7Q44IGxYtCK13bbCb1IiM+6Fmr/rMRAe7W4IbVvNsOft6bdOqDMFatxWtCo0la9NCib8E3IL6+Ig2WgIfZGFOXdkVzbzUWggm0mp3i7vQ7LZEIP0n3+lc173l7iX6S7u7E6LX0nJqzNcWEvkgV4E9iBq9Gq4lLdqYL9k3vI=,iv:6IqnkH4pTqMBGsPqCxSeip7KVD4+SOyLnASscbUVlfo=,tag:hqJFO2t4fbOol4fvM18XhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
