apiVersion: v1
kind: Secret
metadata:
    name: mother-tree-backup-s3
    namespace: mother-tree
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:9DzhWY1JF4AkMTcma23xeCMNFwI=,iv:TsrGFTRqf54guW/xjtcvFhzfulC/jRhLBkH9S6/CoV8=,tag:3tA1pnas52afGY4iZ/LMFQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VJVZlAou0xGRL1lftGnd68nFXVHE1hfi5Yy8GNpVJZ8chkls,iv:KiewcxCotRDi+CB9+MjincsfZTCLR9R/PKFlrSppiBI=,tag:+fDNkihdRWTbCw/2SD4wmg==,type:str]
sops:
    age:
        - recipient: age1ny5rpz82l25pxw3esxrv6e2g5wy3j09uwgmwu6ygh6q9k6jajp3srl0ru5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseXVEMmtZNUxRdWs2Zm8x
            aVRyZUpReDlwK2pFaXBBOXhoZkNGYmRIaEhVCmh6UUVCU2dXb2duYUZaRmFPSWRQ
            NHpXQlphQW93cmVrSWVFUHpPSjd4bVUKLS0tIENFb2pSenRrb3I5Y3Q5dDYrY0pZ
            a1kvVWZBM1FLYzkzNXMweFZSR05ZMGcK6CG5EvgD4/Wb1ER0qvaQ0lz3g5j1PO4i
            UfjkzOK/pyhKM9EbagQ/SwEO4K22OUynKHA4rBM63k31S0UKOkFUXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T13:38:56Z"
    mac: ENC[AES256_GCM,data:dTvB30+52AC7L/2eF7KVKGr1t4aW2He/xXFTppDg2KkVOWROdBgB53lQnD6ce85cWq7PPKzfB170EVzzi5Tt3mSppXVDUJ7LPNdUqgPeDiT81GnOkrfHUjZ03WF/4Idvg2NkesnqL7iBnT+Din3Wbk36DHunbVIo/n6B5TUsK/I=,iv:JgQPyjAfTPdTrTWj2sERVIV6RX2rwfP0x2XCRGxjBz4=,tag:aVYNmWFvU0Pc39Ik059jtA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
