apiVersion: v1
kind: Secret
metadata:
    name: anthropic-api
    namespace: mother-tree
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:CvIjeg90ZOdLMdk5YUEkXV1frUIrBZb9Se90E5mnsBut1DOl5PkVyUZxUGzDfIyfTcjag5uDpaF+7jGoJ8RdS6TTnA+0oZtEZHv5rJmhWPME4f8XgToOoK3q4C45u26VxYG1fxXDr+5mB8u5,iv:wCO4BUBK7md2HmNkqI9d4PrglXsLfEHvQLDyrroVXYQ=,tag:aqHSq0IHOhcYIlGPEXKOew==,type:str]
sops:
    age:
        - recipient: age1ny5rpz82l25pxw3esxrv6e2g5wy3j09uwgmwu6ygh6q9k6jajp3srl0ru5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VnZaRTR4SHpUS2I3T0RS
            S0FIV0lSZmgzYWxhNU91L3MwVG9WZExQbUhNCmU2a3V4RGVSbldFNlNkQUtyS0h4
            S01DZVRkd0dtZCt6R0JWRzVmS01ndGMKLS0tIDFxZnJEYi90ak5FK096dTZMUHBr
            ODZXVnJlQXFmMVg3TS9EVGxidkZGNWMKRaME8CKa1aGKVsTOpyNTdePTORUSIY1B
            FFY2obI7U2Clr9KORU5pbZXZ1y31v/1yduxm5aD0EofMlLQaiez2Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T14:18:27Z"
    mac: ENC[AES256_GCM,data:atZPcIb5W1jf5QoLm7HR426OrwkpRl1lSdiq6wnFWKILwqQNgm4zTAiYErXYxd6mPdUFO9/2vIJYNyXiEAYGBTrono5mjbMyQz3+NCr2WHxxYEKpih2d5pEDKnYj8nLtBWdZk28eMkbve+23dQB3CpZPKUc4UzzkXoL806aa7QA=,iv:+dotH4Qa0CUIFsCWqjrr67tczWWD+dQQG//FVpguGGI=,tag:QOID4EALBFQPcc9SZf9YcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
