apiVersion: v1
kind: Secret
metadata:
    name: scaleway-ai
    namespace: mother-tree
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:yH2BQ5yOinOzDVhF9XT0g9YL1M8=,iv:i+NF1KZM49mZK/eWHf1Kn4+iIgdT6C+b7fIfcrGcKBs=,tag:lEkpNTqz7lxSli6C4jJn/A==,type:str]
    secret-key: ENC[AES256_GCM,data:k+t3SKe25+ey/DPrl59F9Rl/eZ0pQ7ytfp5/5UI3BekQbUex,iv:7ik9WhxOXTTB2cVOR4vThT1y8vGOgwXaLLfVkhF6NCY=,tag:a6q+sIGg0rcO72jnmZrZ0A==,type:str]
sops:
    age:
        - recipient: age1ny5rpz82l25pxw3esxrv6e2g5wy3j09uwgmwu6ygh6q9k6jajp3srl0ru5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTitGYkhPOTBTaFlFNmY1
            ZzBiN3hDK2hncHhBYkFmWGdObG5ZbWY3SFh3CkNEQzRUNzFxR3JqUkZsVGhoMkJB
            Y0RSWjhrSVpoOUhZc0Q2ZEZNMWxmYmMKLS0tIExwdUJOMkNoRTdvVmFwM0VjZEh0
            aDJ0Tmt6czNKZnl1TVc2REpaSnZuYWcKAw2pqsx7BSO1amFRVYJ85fw2PT61TTag
            xBoYaVLkj3r3T2GbEAbKdM7Fyk88xTzcoU6GkF2919v+5dRtG/1PEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T13:38:56Z"
    mac: ENC[AES256_GCM,data:zB3LUYE9NFl38s2J3yBZFpau+k7L5Z3i+XjGRH3eCdI1l91kMxcKyCTZAKn4j/0Wd/uuuEVJAfc9wdoyMmsAM3bgxeU3itQ/fQAQ1nIe45b0hiXUPFLIIL3RnLDpAW+iDJaY9nshwflO+GleVkd//CEYHvCAscfCJOQaRgS5Y2A=,iv:ICw7DIH7V8RO8QKAJxatVdKUmygopxv7YLbVIDRYozQ=,tag:KZ/Y6EAapjgOHVJ0dFE9Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
