apiVersion: v1
kind: Secret
metadata:
    name: hasura-admin-secret
    namespace: mother-tree
type: Opaque
stringData:
    admin-secret: ENC[AES256_GCM,data:URKmUnMw1mXpfyAvP2P8u04tMCB8hOg9EF06oQskNiimK0SqG25mn3ckkA==,iv:Ilovj0/3VNrT/uZY/eCxOnejktgTXkpbEkWJUO6oY9M=,tag:MeESgpd/R3X1cfur3kRfZg==,type:str]
sops:
    age:
        - recipient: age1ny5rpz82l25pxw3esxrv6e2g5wy3j09uwgmwu6ygh6q9k6jajp3srl0ru5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN2dvY2dTMzhoWFcxMWdq
            a1FOWHQ3NjlSdXArZ3ZTcVVMS3EvdlhNQ1FFCkxVTFVIQ3lmUFh3aHFWL0Vxb3Z6
            djdyWXZKY0ptTlFwdDFUbXA4YVBlQmsKLS0tIDhCTGNFMFI3amNvZU1UUlVsb0ho
            bHdlVEdzT3l0ZCtxNkV0S2xtYU5tck0KDp7UxSk1n6Ud+5/93dQZnikSP5pQqbDO
            d2FZqTzGg5ZWDfHvrLENW22C5GhN7nMiO+ygqPwLzJZLS8UfM+tAyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-18T13:38:56Z"
    mac: ENC[AES256_GCM,data:aiSZWp61b2Pu/3iVg+SQ+rQQw4EbpZ9vE2k4Hn0fvAZy7IsJSPW6hUl0D+E98oGiaXnGm4nGoAClu9hyS/gO3SnSEKQAY315KQ46GhMt44EqSiUfdBg+WPBezNC6iJJzeE3o90OTBXdtNWZ7TeKNl9Jx8TDl+caTBpNUPNNZr1c=,iv:8j5qJyx1L9ISduOLavWV/a5mzaYsqr89D3GedAT+TSQ=,tag:S6KFta97+f5TOz+AS5QfRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
