apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8WgK9UtvjIz6JPO+7xiK6C0g85Vb8oqbD44U3Sp49cimGJ/hxyUOkMKPONU55a2Ehx09t0wkGcAXyqoy0tjv3ve3UAmypQONLZAqv1F3TAYCU35de90cEWESRFslq5XcDlX2BTnvlX2b+DcpLZB39ltVSpIr0mfx7CJRy5dLr7LUzyoXdqj/rKZ9EBLT5ssefwOrHDc7kBgO3XaCt3HrZjafJiOLvDtonW9WU5KG5s8ItkrtMcdFj4EPF9T3lYeQE98zVnikgB0E01XL+Qqm8IrqsBHHsX9Rq83Cz8gwtO+Ht2sQXs3HSrv1r8ZkTBkMDHQTTxc6dKN5WkGkF288/gRjV2k=,iv:NORQ1E4DbAwOuTcs6duW5eXGtlquscc/nEVpCDTtT/U=,tag:4AlBBH15K4Lfjnru/Zdx2w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: gitlab-registry
    namespace: mother-tree
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1ny5rpz82l25pxw3esxrv6e2g5wy3j09uwgmwu6ygh6q9k6jajp3srl0ru5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOGhmcGxiRU8wQkZ0elpO
            RFBLWE1wWFFIVFNCbE1oaFVPbGJyY0UrVGdzCmdrQzRVT1VyYWgrVFBXb1IxWTEr
            czVJT1BkMFFRWCs2ZkJPeVVPSFZmTVkKLS0tIDN1OHMxODFmRUx4bVJ1Ynd1d3Ax
            NG5xaGxackt6VzUyZnNSTVB2ell5dWsKbIHuk/yjDBdgd6vcC6EaT4TVwZfO7r9u
            ShHvQiHK09fi/qo9gUhMCTZJPtQoyE35Flz8EWeIDt+fLL8YySSnBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T07:01:40Z"
    mac: ENC[AES256_GCM,data:Bx7zh0LKu7tkmjalZ38UYj1iIQaWV//M03KqoSusJYD9c9oHEC3mVj40rt4kjOUXl0P/O5CTLWzwNvaQbeGkNuFVtlDvnzp8urzMGjrS715TJeB0ERL3jvwhWj/KauPqGQKKkPe5Vul88+mzIJ6NFZEs13t1M0NT4/sKCZkcxBk=,iv:tj3wZpq1eRPmn9R1ppcCE8eRinoVEvOdW4DjGmuH0Ek=,tag:ygrGt4ec42kVtG9qXeV1xA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
